### ISSUE TITLE
OAuth2 Error

### ISSUE THREAD

**Issue by krtko1** [matuszelenak/trojsten-graph#13]
![2020-02-01-101450_grim](https://user-images.githubusercontent.com/21214184/73589980-40921c80-44dd-11ea-99c5-f41ee25f533c.png)

**Comment by matuszelenak** [comment]
hm, to bude tym, ze si na trojsten.wtf a nie na graph.trojsten.wtf
Sice som nastavil, ze vsetky poddomeny trojsten.wtf smeruju na to iste, ale googlu auth configuracii to tak povedat neviem :/
